package com.beniregev.demos;

public class Compare2StringsDemo {
    private final String str1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><report:providerEngagementReport xmlns:report=\"http://caretalks.americanwell.com/IET/2007/12\" Customer=\"1\" Locale=\"en_US\"><report:Title>engagement.title.assistant.top</report:Title><report:pharmacyPhone/><report:pharmacyFax/><report:DateTime>5/1/19 12:00:00 AM EDT</report:DateTime><report:ProviderView>true</report:ProviderView><report:proxyView>false</report:proxyView><report:guarantor>Bob LastName</report:guarantor><report:engagement-rating>0</report:engagement-rating><report:provider-rating>0</report:provider-rating><report:hasTriageQuestions>false</report:hasTriageQuestions><report:hasPractice>false</report:hasPractice><report:isTransfer>false</report:isTransfer><report:isMultiCountry>true</report:isMultiCountry><report:automaticVisitExportAtWrapUP>false</report:automaticVisitExportAtWrapUP><report:tmtVisitWithStaff>false</report:tmtVisitWithStaff><report:tmtVisit>false</report:tmtVisit><report:HasTytoExamData>true</report:HasTytoExamData><report:showGuestList>false</report:showGuestList><report:patient><report:details><report:name>Bob LastName</report:name></report:details><report:phone>+1 (617) 555-5555</report:phone><report:mailingAddress><report:mailAddress1>1331 main st</report:mailAddress1><report:mail-city-state-zip>downtown, MA 02111</report:mail-city-state-zip><report:mailCountry>United States</report:mailCountry></report:mailingAddress></report:patient><report:provider><report:details><report:name>ProviderFirstName I. ProviderLastName</report:name></report:details><report:address><report:address1>1331 main st</report:address1><report:city-state-zip>downtown, MA 02111</report:city-state-zip></report:address><report:phone>+1 (800) 555-5555</report:phone></report:provider><report:Summary><report:CoPay><report:Amt>100.0</report:Amt><report:PaymentType/></report:CoPay><report:Topics><report:Topic><report:AddedBy>agenda.addedBy.colon.withTime</report:AddedBy><report:Title>title</report:Title><report:Description/></report:Topic></report:Topics><report:Triage/></report:Summary><report:document><report:chatItems/><report:accounts/><report:exams><report:examDatum><report:type>Mouth</report:type><report:dateTime>May 01, 2017 at 10:25 AM EDT</report:dateTime></report:examDatum></report:exams></report:document><report:engagementBlobs><report:ProviderNotes/></report:engagementBlobs><report:engagementBlobs><report:ProviderPrivateNotes/></report:engagementBlobs><report:providerDiagnosesAndProcedures><report:providerTerms/></report:providerDiagnosesAndProcedures><report:engagementRx><report:prescriptions/></report:engagementRx><report:providerAllergens><report:providerTerms/></report:providerAllergens><report:providerObservations><report:providerTerms/></report:providerObservations><report:followUpItems/><report:practiceFollowUps/><report:postVisitItems/><report:dssContent/><report:disclaimer/><report:epicAppts/></report:providerEngagementReport>";
    private final String str2 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><report:providerEngagementReport xmlns:report=\"http://caretalks.americanwell.com/IET/2007/12\" Customer=\"1\" Locale=\"en_US\"><report:Title>engagement.title.assistant.top</report:Title><report:pharmacyPhone/><report:pharmacyFax/><report:DateTime>5/1/19 12:00:00 AM EST</report:DateTime><report:ProviderView>true</report:ProviderView><report:proxyView>false</report:proxyView><report:guarantor>Bob LastName</report:guarantor><report:engagement-rating>0</report:engagement-rating><report:provider-rating>0</report:provider-rating><report:hasTriageQuestions>false</report:hasTriageQuestions><report:hasPractice>false</report:hasPractice><report:isTransfer>false</report:isTransfer><report:isMultiCountry>true</report:isMultiCountry><report:automaticVisitExportAtWrapUP>false</report:automaticVisitExportAtWrapUP><report:tmtVisitWithStaff>false</report:tmtVisitWithStaff><report:tmtVisit>false</report:tmtVisit><report:HasTytoExamData>true</report:HasTytoExamData><report:showGuestList>false</report:showGuestList><report:patient><report:details><report:name>Bob LastName</report:name></report:details><report:phone>+1 (617) 555-5555</report:phone><report:mailingAddress><report:mailAddress1>1331 main st</report:mailAddress1><report:mail-city-state-zip>downtown, MA 02111</report:mail-city-state-zip><report:mailCountry>United States</report:mailCountry></report:mailingAddress></report:patient><report:provider><report:details><report:name>ProviderFirstName I. ProviderLastName</report:name></report:details><report:address><report:address1>1331 main st</report:address1><report:city-state-zip>downtown, MA 02111</report:city-state-zip></report:address><report:phone>+1 (800) 555-5555</report:phone></report:provider><report:Summary><report:CoPay><report:Amt>100.0</report:Amt><report:PaymentType/></report:CoPay><report:Topics><report:Topic><report:AddedBy>agenda.addedBy.colon.withTime</report:AddedBy><report:Title>title</report:Title><report:Description/></report:Topic></report:Topics><report:Triage/></report:Summary><report:document><report:chatItems/><report:accounts/><report:exams><report:examDatum><report:type>Mouth</report:type><report:dateTime>May 01, 2017 at 10:25 AM EDT</report:dateTime></report:examDatum></report:exams></report:document><report:engagementBlobs><report:ProviderNotes/></report:engagementBlobs><report:engagementBlobs><report:ProviderPrivateNotes/></report:engagementBlobs><report:providerDiagnosesAndProcedures><report:providerTerms/></report:providerDiagnosesAndProcedures><report:engagementRx><report:prescriptions/></report:engagementRx><report:providerAllergens><report:providerTerms/></report:providerAllergens><report:providerObservations><report:providerTerms/></report:providerObservations><report:followUpItems/><report:practiceFollowUps/><report:postVisitItems/><report:dssContent/><report:disclaimer/><report:epicAppts/></report:providerEngagementReport>";

    public String getStr1() {
        return str1;
    }

    public String getStr2() {
        return str2;
    }

    public static void main(String[] args) {
        Compare2StringsDemo compare2StringsDemo = new Compare2StringsDemo();
        char[] chars1 = compare2StringsDemo.getStr1().toCharArray();
        char[] chars2 = compare2StringsDemo.getStr2(). toCharArray();

        for(int i=0; i < chars1.length ; i++) {
            if (chars1[i] != chars2[i]) {
                System.out.println("Possition #" + i + ": chars1='" + chars1[i] + "' and chars2='" + chars2[i] + "' - not a match!");
            }
        }
        System.out.println("Finished!");
    }
}
